### PR TITLE
callout to the new colab release

### PR DESCRIPTION
**Pull request by rgbkrk**
/cc @craigcitro @Carreau @captainsafia

### CODE REVIEW

**Comment by captainsafia** [comment]
Good idea! Will clarify things for people in the community.

**Comment by craigcitro** [comment]
👍 🎉 

Thanks so much!

**Comment by Carreau** [comment]
+1; I didn't had the chance to try the new version yet, but heard only good things !

Should we also do a quick post on the jupyter blog, or wait the final release ?

**Comment by craigcitro** [comment]
@Carreau let's wait for now; I may come back asking about that at some point. 😁

**Pull request merged**
